function output = getOrientationSelectiveOutput(inputImage,filterparams,lambda,theta)

if strcmp(filterparams.name,'Gabor')
    inhibition.method = filterparams.inhibMethod;
    inhibition.alpha  = filterparams.inhibAlpha;
    
    output = computeGaborEnergy(inputImage,...
        lambda,...
        filterparams.aspectratio,...
        filterparams.bandwidth,...
        {theta},...
        filterparams.phaseoffset,...
        filterparams.halfwave,...
        2,...
        inhibition,...
        10,...
        filterparams.thinning,...
        filterparams.t0);
else
    error('Input filter type not handled by the system');
end